config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  devise_for :users
  root "documents#index"
  resources :documents do
    resource :likes, only: [:create, :destroy]
  end
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :document
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  def liked_by?(user)
    likes.any? {|like| like.user_id == user.id}
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :document, counter_cache: :likes_count
  validates :user_id, uniqueness: {
    scope: :document_id,
    message: "は同じ投稿に2回以上いいねはできません"
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :documents, dependent: :nullify
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_documents, through: :likes, source: :document

  def already_liked?(document)
    self.likes.exists?(document_id: document.id)
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
    user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: [:index, :show]
  PER_PAGE = 5

  def index
    @q = Document.ransack(params[:q])
    @documents = @q.result.includes(:user, :likes).order(created_at: :desc).page(params[:page]).per(PER_PAGE)
  end

  def show
  end

  def new
    @document = Document.new
  end

  def create
    document = current_user.documents.create!(document_params)
    redirect_to document, notice: "投稿しました"
  end

  def edit
  end

  def update
    @document.update!(document_params)
    redirect_to @document, notice: "更新しました"
  end

  def destroy
    @document.destroy!
    redirect_to root_path, alert: "削除しました"
  end

  private

    def document_params
      params.require(:document).permit(:title, :body)
    end

    def set_document
      @document = Document.find(params[:id])
    end

    def after_sign_out_path_for(resource)
      document_path
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    current_user.likes.create!(document_id: params[:document_id])
    @document = Document.find(params[:document_id])
  end

  def destroy
    current_user.likes.find_by(document_id: params[:document_id]).destroy!
    @document = Document.find(params[:document_id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_dislike.html.erb
<%= link_to document_likes_path(document), method: :post, remote: true do %>
<i class="far fa-thumbs-up fa-lg"></i>
<%= document.likes_count %>
<% end %>

app/views/documents/_form.html.erb
<%= form_with model:@document, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title, class: "form-control", placeholder:"タイトルを入力してください" %>
  </div>
  <div class="form-group">
    <%= form.label :body, "本文" %>
    <%= form.text_area :body, class: "form-control", placeholder:"本文を入力してください", rows: 10 %>
  </div>
  <div>
    <%= form.submit botton_value, class: "btn btn-primary btn-block" %>
  <div>
<% end %>

app/views/documents/_like.html.erb
<%= link_to document_likes_path(document), method: :delete, remote: true do %>
<i class="fas fa-thumbs-up fa-lg"></i>
<%= document.likes_count %>
<% end %>

app/views/documents/edit.html.erb
<h1>編集</h1>
<%= render "form", botton_value: "更新" %>

app/views/documents/index.html.erb
<h1 class="text-center">投稿一覧</h1>
<div class="search-control">
  <%= search_form_for @q do |f| %>
    <%= f.label :title_cont, "検索" %>
    <%= f.search_field :title_cont,  placeholder: "タイトルを入力" %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<div class="container container-top">
  <div>
    <% @documents.each do |document| %>
      <td>
        <%= l document.created_at %>に投稿
        <h3>
        <%= link_to document.title, document, :style=>"color:black;" %>
        </h3>
        <% if current_user.id == document.user_id %>
          <%= link_to "削除", document, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-danger btn-sm"  %>
          <%= link_to "編集", edit_document_path(document), class: "btn btn-outline-primary  btn-sm" %>
        <% end %>
        <p id="document-<%= document.id %>">
          <% if document.liked_by?(current_user) %>
            <%= render "like", document: document %>
          <% else %>
            <%= render "dislike", document: document %>
          <% end %>
        </p>
        <hr>
      </td>
    <% end %>
  </div>
  <%= paginate @documents %>
</div>

app/views/documents/new.html.erb
<h1>新規投稿</h1>
<%= render "form", botton_value: "投稿" %>

app/views/documents/show.html.erb
<h1 class="text-center">記事詳細</h1>
<h6 div="text-right"><%= l @document.created_at %>に投稿
<div class="card card-document border-dark mt-5">
  <div class="card-header">
    <h4><%= @document.title %></h4>
    <p id="document-<%= @document.id %>">
    <% if @document.liked_by?(current_user) %>
      <%= render "like", document: @document %>
    <% else %>
      <%= render "dislike", document: @document %>
    <% end %>
    </p>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(h @document.body) %></p>
  </div>
</div>
  <% if current_user.id == @document.user_id %>
    <p>
      <%= link_to "削除", document_path(@document), method: :delete, date: { confirm: "削除しますか？" }, class: "btn btn-danger btn-sm" %>
      <%= link_to "編集", edit_document_path(@document), class: "btn btn-outline-primary btn-sm" %>
    </p>
  <% end %>
  <p><%= link_to "戻る", documents_path, class: "btn btn-info active btn-block" %></p>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-info" >
  <%= link_to "情報共有サイト", top_index_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto ">
      <% if user_signed_in? %>
        <%= link_to "新規投稿", new_document_path, class: "nav-item nav-link active" %>
        <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active" %>
        <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, date: { confirm: "ログアウトしますか？" } %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active" %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
        <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "nav-item nav-link active", method: :post %>
      <% end %>
      <hr>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InformationShareSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('document-<%= @document.id %>').innerHTML = '<%= j render("documents/like", document: @document) %>'

app/views/likes/destroy.js.erb
document.getElementById('document-<%= @document.id %>').innerHTML = '<%= j render("documents/dislike", document: @document) %>'

app/views/top/index.html.erb
<div class="card-top">
  <div class="row no-gutters">
    <div class="col-md-6">
      <div class="card-body">
        <h1 class="card-title">情報共有サイト</h1>
        <h3 class="card-subtitle">
          養護教諭のための<br>
          様々な情報を共有するサイト
        </h3>
        <p class="card-text">
          養護教諭の仕事のやり方や仕事に対する悩みを共有し、<br>
          少しでも不安や悩みを解消出来ればと思い開発しました。
        </p>
          <div class="btn-group-vertical float-right">
              <%= link_to "ログイン", documents_path, class: "btn-top btn-redius text-white text-decoration-none" %>
              <%= link_to "ログインせずに記事のみ確認", users_guest_sign_in_path, class: "btn-sm text-decoration-none mt-2 btn-outline-primary", method: :post %>
          </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag "https://wp.notepm.jp/wp-content/uploads/2020/01/info-tool-3.jpg", size: "470x400", alt:"情報共有画像" %>
    </div>
  </div>
</div>